name: spring26cnsproject
channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _python_abi3_support=1.0=hd8ed1ab_2
  - asttokens=3.0.1=pyhd8ed1ab_0
  - binutils_impl_linux-64=2.45=default_hfdba357_105
  - binutils_linux-64=2.45=default_h4852527_105
  - brian2=2.10.1=py314h3a4f467_1
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - comm=0.2.3=pyhe01879c_0
  - cpython=3.14.2=py314hd8ed1ab_101
  - cython=3.2.4=py314h1807b08_0
  - debugpy=1.8.20=py314h42812f9_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - gcc_impl_linux-64=14.3.0=he8b2097_16
  - gcc_linux-64=14.3.0=h298d278_17
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.2.1=py314h28848ee_2
  - gsl=2.8=hbf7d49c_1
  - gxx_impl_linux-64=14.3.0=h2185e75_16
  - gxx_linux-64=14.3.0=h310e576_17
  - icu=78.2=h33c6efd_0
  - ipykernel=7.1.0=pyha191276_0
  - ipython=9.10.0=pyh53cf698_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhcf101f3_1
  - jupyter_client=8.8.0=pyhcf101f3_0
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - kernel-headers_linux-64=3.10.0=he073ed8_18
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_105
  - libblas=3.11.0=5_h4a7cf45_openblas
  - libcblas=3.11.0=5_h0358290_openblas
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h3435931_0
  - libgcc=15.2.0=he0feb66_16
  - libgcc-devel_linux-64=14.3.0=hf649bbc_116
  - libgcc-ng=15.2.0=h69a702a_16
  - libgfortran=15.2.0=h69a702a_16
  - libgfortran5=15.2.0=h68bc16d_16
  - libgomp=15.2.0=he0feb66_16
  - liblapack=3.11.0=5_h47877c9_openblas
  - liblzma=5.8.2=hb03c661_0
  - libmpdec=4.0.0=hb03c661_1
  - libopenblas=0.3.30=pthreads_h94d23a6_4
  - libsanitizer=14.3.0=h8f1669f_16
  - libsodium=1.0.20=h4ab18f5_0
  - libsqlite=3.51.2=hf4e2dac_0
  - libstdcxx=15.2.0=h934c35e_16
  - libstdcxx-devel_linux-64=14.3.0=h9f08a49_116
  - libstdcxx-ng=15.2.0=hdf11a46_16
  - libuuid=2.41.3=h5347b49_0
  - libzlib=1.3.1=hb9d3cd8_2
  - markupsafe=3.0.3=pyh7db6752_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpmath=1.3.0=pyhd8ed1ab_1
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - numpy=2.4.2=py314h2b28147_1
  - openssl=3.6.1=h35e630c_1
  - packaging=26.0=pyhcf101f3_0
  - parso=0.8.5=pyhcf101f3_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pip=26.0=pyh145f28c_0
  - platformdirs=4.5.1=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.2.2=py314h0f05182_0
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.3.2=pyhcf101f3_0
  - python=3.14.2=h32b2ec7_101_cp314
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-gil=3.14.2=h4df99d1_101
  - python_abi=3.14=8_cp314
  - pyzmq=27.1.0=py312hfb55c3c_0
  - readline=8.3=h853b02a_0
  - scipy=1.17.0=py314hf07bd8e_1
  - setuptools=80.10.2=pyh332efcf_0
  - six=1.17.0=pyhe01879c_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - sympy=1.14.0=pyh2585a3b_105
  - sysroot_linux-64=2.17=h0157908_18
  - tk=8.6.13=noxft_h366c992_103
  - tornado=6.5.4=py314h7b0bd38_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025c=hc9c84f9_1
  - wcwidth=0.5.3=pyhd8ed1ab_0
  - zeromq=4.3.5=h387f397_9
  - zstd=1.5.7=hb78ec9c_6
  - pip:
      - iniconfig==2.3.0
      - pluggy==1.6.0
      - pytest==9.0.2
