name: spring26cnsproject
channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - binutils_impl_linux-64=2.45=default_hfdba357_105
  - binutils_linux-64=2.45=default_h4852527_105
  - brian2=2.10.1=py314h2a0892c_1
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cpython=3.14.2=py314hd8ed1ab_1
  - cython=3.2.4=py314h3f98dc2_0
  - gcc_impl_linux-64=14.3.0=he8b2097_16
  - gcc_linux-64=14.3.0=h298d278_17
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.2.1=py314h1d7fe96_2
  - gsl=2.8=hbf7d49c_1
  - gxx_impl_linux-64=14.3.0=h2185e75_16
  - gxx_linux-64=14.3.0=h310e576_17
  - icu=78.2=h33c6efd_0
  - jinja2=3.1.6=pyhcf101f3_1
  - kernel-headers_linux-64=3.10.0=he073ed8_18
  - ld_impl_linux-64=2.45=default_hbd61a6d_105
  - libblas=3.11.0=5_h4a7cf45_openblas
  - libcblas=3.11.0=5_h0358290_openblas
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h3435931_0
  - libgcc=15.2.0=he0feb66_16
  - libgcc-devel_linux-64=14.3.0=hf649bbc_116
  - libgcc-ng=15.2.0=h69a702a_16
  - libgfortran=15.2.0=h69a702a_16
  - libgfortran5=15.2.0=h68bc16d_16
  - libgomp=15.2.0=he0feb66_16
  - liblapack=3.11.0=5_h47877c9_openblas
  - liblzma=5.8.2=hb03c661_0
  - libmpdec=4.0.0=hb03c661_1
  - libopenblas=0.3.30=pthreads_h94d23a6_4
  - libsanitizer=14.3.0=h8f1669f_16
  - libsqlite=3.51.2=hf4e2dac_0
  - libstdcxx=15.2.0=h934c35e_16
  - libstdcxx-devel_linux-64=14.3.0=h9f08a49_116
  - libstdcxx-ng=15.2.0=hdf11a46_16
  - libuuid=2.41.3=h5347b49_0
  - libzlib=1.3.1=hb9d3cd8_2
  - markupsafe=3.0.3=pyh7db6752_0
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpmath=1.3.0=pyhd8ed1ab_1
  - ncurses=6.5=h2d0b736_3
  - numpy=2.4.2=py314hd4f4903_1
  - openssl=3.6.1=h35e630c_1
  - packaging=26.0=pyhcf101f3_0
  - pip=26.0=pyh145f28c_0
  - pyparsing=3.3.2=pyhcf101f3_0
  - python=3.14.2=he1279bd_1_cp314t
  - python_abi=3.14=8_cp314t
  - readline=8.3=h853b02a_0
  - scipy=1.17.0=py314h529d2a9_1
  - setuptools=80.10.2=pyh332efcf_0
  - sympy=1.14.0=pyh2585a3b_105
  - sysroot_linux-64=2.17=h0157908_18
  - tk=8.6.13=noxft_h366c992_103
  - tzdata=2025c=hc9c84f9_1
  - zstd=1.5.7=hb78ec9c_6
